### ISSUE TITLE
How Do I convert the type from the processing sketch with the opacity to the solid colors I see in your website?

### ISSUE THREAD

**Issue by Jodastt** [dannewoo/TypeGalapagos#1]
So I saw the thumbnail here (http://dannewoo.com/projects/typegalapagos.html) and I thought the typography was really cool, but when I downloaded the source code and tried it myself, I found no way to export the letters or make them solid like the thumbnail.  How do I do this?

**Comment by dannewoo** [comment]
Thanks @Jodastt . Its been a very long time since I looked at this project, but I believe if you hit 'P' when you run the sketch it will export a PDF of the visible letterforms.

**Comment by Jodastt** [comment]
Okay, thanks.  Will they be solid?

**Comment by dannewoo** [comment]
Yeah. They will be in a vector format so you can open it in something like Illustrator and modify it further.

**Comment by Jodastt** [comment]
Okay, thanks a lot!
